server.port=8081
spring.application.name=hbdeskhelp-api

spring.datasource.url=jdbc:h2:file:./data/hbdeskhelp
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Configurações do Cornelius AI
ollama.api.url=http://localhost:11434/api/generate
ollama.model=llama3 # Substitua pelo modelo que você usa no Ollama, ex: llama3, mistral, phi3

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
gemini.api.key=COLOQUE_SUA_CHAVE_AQUI
